-- Exemplo de Qualidade (pendências, FVS, Gemba). Só roda se as tabelas estiverem vazias.
do $seed$ begin
if exists (select 1 from public.fvs_modelos) or exists (select 1 from public.qualidade_pendencias) then return; end if;

insert into public.fvs_modelos (id, codigo, nome, categoria, versao, grupos) values
('c15c2894-22b1-4997-ba7f-80c70a7a0052', 'FVS-01', 'Impermeabilização — Áreas Molhadas', 'Impermeabilização', 2, '[{"nome":"Pré-execução","itens":[{"id":101,"titulo":"Substrato limpo, seco e sem falhas"},{"id":102,"titulo":"Caimento do contrapiso em direção ao ralo conferido"},{"id":103,"titulo":"Cantos e arestas arredondados (meia-cana executada)"}]},{"nome":"Execução","itens":[{"id":104,"titulo":"Primer aplicado em toda a área"},{"id":105,"titulo":"Número de demãos conforme o projeto"},{"id":106,"titulo":"Reforço com tela nos ralos e rodapés"},{"id":107,"titulo":"Subida da impermeabilização no rodapé com no mínimo 30 cm"}]},{"nome":"Proteção e acabamento","itens":[{"id":108,"titulo":"Teste de estanqueidade por 72 h sem vazamento"},{"id":109,"titulo":"Proteção mecânica executada sobre a manta"}]}]'::jsonb),
('14ba7680-2f00-47da-8ccd-bd06097e98e0', 'FVS-02', 'Revestimento Cerâmico', 'Acabamento', 1, '[{"nome":"Preparo da base","itens":[{"id":201,"titulo":"Base nivelada, limpa e curada"},{"id":202,"titulo":"Argamassa colante adequada ao formato da peça"},{"id":203,"titulo":"Paginação conferida com o projeto"}]},{"nome":"Aplicação e acabamento","itens":[{"id":204,"titulo":"Colagem dupla em peças grandes"},{"id":205,"titulo":"Juntas uniformes e alinhadas"},{"id":206,"titulo":"Ausência de peças ocas (teste de percussão)"},{"id":207,"titulo":"Rejunte aplicado e superfície limpa"}]}]'::jsonb);

insert into public.qualidade_pendencias (obra_id, numero_registro, descricao, local, pavimento, empresa, prazo, responsavel, data_vistoria, vistoriado_por, status, data_resolucao, observacoes) values
((select id from public.obras where codigo = 'U12'), 1, 'Solda do spool 14 com respingos e sem acabamento na linha L-340.', 'Linha L-340', 'Rack 3', 'Metalúrgica Alfa', '2026-10-02', 'Carlos Menezes', '2026-09-28', 'Ana Souza', 'pendente', null, '[30/09/2026 09:12] Empresa pediu mais 2 dias por falta de esmerilhadeira.
[28/09/2026 15:40] Registrado na vistoria de rotina.'),
((select id from public.obras where codigo = 'T405'), 1, 'Chapa do fundo do tanque com empeno acima do tolerado.', 'Fundo do tanque T-405', 'Anel 1', 'Metalúrgica Alfa', '2026-10-10', 'Rafael Lima', '2026-10-03', 'Rafael Lima', 'pendente', null, ''),
((select id from public.obras where codigo = 'U12'), 2, 'Escorrimento de tinta na segunda demão do pórtico P-3.', 'Pórtico P-3', 'Cota 8 m', 'Pinturas Beta', '2026-10-04', 'Juliana Prado', '2026-09-29', 'Ana Souza', 'em_andamento', null, '[03/10/2026 16:05] Lixamento feito, falta a nova demão.'),
((select id from public.obras where codigo = 'T405'), 2, 'Cordão de solda com porosidade visível na junta 7.', 'Costado T-405', 'Junta 7', 'Metalúrgica Alfa', '2026-10-06', 'Rafael Lima', '2026-10-01', 'Rafael Lima', 'em_andamento', null, '[03/10/2026 13:45] Esmerilhado, aguardando reparo e novo ensaio.'),
((select id from public.obras where codigo = 'U12'), 3, 'Guarda-corpo da plataforma do forno F-101 sem rodapé.', 'Forno F-101', 'Plataforma norte', 'Metalúrgica Alfa', '2026-10-07', 'Carlos Menezes', '2026-10-02', 'Ricardo Lopes', 'pendente', null, ''),
((select id from public.obras where codigo = 'U12'), 4, 'Eletroduto sem fixação no trecho que chega ao painel PC-12.', 'Painel PC-12', '', 'Elétrica Gama', '2026-10-09', 'Juliana Prado', '2026-10-01', 'Ana Souza', 'em_andamento', null, '[03/10/2026 08:30] Braçadeiras compradas, instalação amanhã.'),
((select id from public.obras where codigo = 'U12'), 5, 'Isolamento térmico danificado em trecho da linha L-212.', 'Linha L-212', 'Rack 1', 'Pinturas Beta', '2026-09-30', 'Juliana Prado', '2026-09-25', 'Ricardo Lopes', 'resolvido', '2026-10-01', '[01/10/2026 11:20] Trecho refeito e conferido com a fiscalização.
[25/09/2026 14:10] Vistoria: manta rasgada por passagem de andaime.'),
((select id from public.obras where codigo = 'U12'), 6, 'Tubulação de água de resfriamento sem sinalização de fluxo.', 'Casa de bombas', '', 'Pinturas Beta', '2026-10-12', 'Juliana Prado', '2026-10-03', 'Ana Souza', 'pendente', null, '');

insert into public.fvs_vistorias (id, obra_id, modelo_id, modelo_codigo, modelo_nome, versao, ambiente, grupos, respostas, status, criada_em, criada_por, concluida_em, empresa) values
('cf534d5f-9f40-4897-a745-f1fe3992c196', (select id from public.obras where codigo = 'U12'), '14ba7680-2f00-47da-8ccd-bd06097e98e0', 'FVS-02', 'Revestimento Cerâmico', 1, 'Cozinha · Térreo', '[{"nome":"Preparo da base","itens":[{"id":201,"titulo":"Base nivelada, limpa e curada"},{"id":202,"titulo":"Argamassa colante adequada ao formato da peça"},{"id":203,"titulo":"Paginação conferida com o projeto"}]},{"nome":"Aplicação e acabamento","itens":[{"id":204,"titulo":"Colagem dupla em peças grandes"},{"id":205,"titulo":"Juntas uniformes e alinhadas"},{"id":206,"titulo":"Ausência de peças ocas (teste de percussão)"},{"id":207,"titulo":"Rejunte aplicado e superfície limpa"}]}]'::jsonb, '{"201":"ok","202":"ok","203":"ok","204":"ok","205":"nc","206":"nc","207":"na"}'::jsonb, 'concluida', '2026-09-28', 'Ana Souza', '2026-09-29', 'Elétrica Gama'),
('ef099cfe-4e15-4e38-a4e6-92644a8db27c', (select id from public.obras where codigo = 'U12'), 'c15c2894-22b1-4997-ba7f-80c70a7a0052', 'FVS-01', 'Impermeabilização — Áreas Molhadas', 2, 'Banheiro Social · Térreo', '[{"nome":"Pré-execução","itens":[{"id":101,"titulo":"Substrato limpo, seco e sem falhas"},{"id":102,"titulo":"Caimento do contrapiso em direção ao ralo conferido"},{"id":103,"titulo":"Cantos e arestas arredondados (meia-cana executada)"}]},{"nome":"Execução","itens":[{"id":104,"titulo":"Primer aplicado em toda a área"},{"id":105,"titulo":"Número de demãos conforme o projeto"},{"id":106,"titulo":"Reforço com tela nos ralos e rodapés"},{"id":107,"titulo":"Subida da impermeabilização no rodapé com no mínimo 30 cm"}]},{"nome":"Proteção e acabamento","itens":[{"id":108,"titulo":"Teste de estanqueidade por 72 h sem vazamento"},{"id":109,"titulo":"Proteção mecânica executada sobre a manta"}]}]'::jsonb, '{"101":"ok","102":"ok","103":"nc","104":"ok","105":"nc"}'::jsonb, 'em_andamento', '2026-10-02', 'Ricardo Lopes', null, 'Elétrica Gama'),
('6b54e996-f731-43be-aae5-f8560fab01cf', (select id from public.obras where codigo = 'T405'), 'c15c2894-22b1-4997-ba7f-80c70a7a0052', 'FVS-01', 'Impermeabilização — Áreas Molhadas', 2, 'Piso do tanque · Anel 1', '[{"nome":"Pré-execução","itens":[{"id":101,"titulo":"Substrato limpo, seco e sem falhas"},{"id":102,"titulo":"Caimento do contrapiso em direção ao ralo conferido"},{"id":103,"titulo":"Cantos e arestas arredondados (meia-cana executada)"}]},{"nome":"Execução","itens":[{"id":104,"titulo":"Primer aplicado em toda a área"},{"id":105,"titulo":"Número de demãos conforme o projeto"},{"id":106,"titulo":"Reforço com tela nos ralos e rodapés"},{"id":107,"titulo":"Subida da impermeabilização no rodapé com no mínimo 30 cm"}]},{"nome":"Proteção e acabamento","itens":[{"id":108,"titulo":"Teste de estanqueidade por 72 h sem vazamento"},{"id":109,"titulo":"Proteção mecânica executada sobre a manta"}]}]'::jsonb, '{"101":"ok","102":"nc"}'::jsonb, 'em_andamento', '2026-10-03', 'Rafael Lima', null, 'Metalúrgica Alfa');

insert into public.fvs_ncs (obra_id, codigo, vistoria_id, item_id, item_numero, titulo, servico, ambiente, severidade, responsavel, empresa, descricao, solucao, status, aberta_em, fechada_em, timeline) values
((select id from public.obras where codigo = 'U12'), 'NC-001', 'cf534d5f-9f40-4897-a745-f1fe3992c196', 205, '2.2', 'Juntas uniformes e alinhadas', 'Revestimento Cerâmico', 'Cozinha · Térreo', 'Baixa', 'Carlos Menezes', 'Metalúrgica Alfa', 'Juntas com largura irregular na parede da pia.', 'Refazer o alinhamento das 6 peças e rejuntar.', 'fechada', '2026-09-29', '2026-10-01', '[{"em":"29/09/2026 14:18","texto":"Aberta por Ana Souza"},{"em":"29/09/2026 16:02","texto":"Encaminhada para Carlos Menezes por Ana Souza"},{"em":"30/09/2026 17:40","texto":"Marcada como corrigida por Carlos Menezes"},{"em":"01/10/2026 09:15","texto":"Aprovada e fechada por Ana Souza"}]'::jsonb),
((select id from public.obras where codigo = 'U12'), 'NC-002', 'cf534d5f-9f40-4897-a745-f1fe3992c196', 206, '2.3', 'Ausência de peças ocas (teste de percussão)', 'Revestimento Cerâmico', 'Cozinha · Térreo', 'Alta', 'Carlos Menezes', 'Metalúrgica Alfa', 'Som oco em 4 peças do piso, perto da porta.', 'Remover as peças, recolar com colagem dupla e repetir o teste.', 'corrigida', '2026-09-29', null, '[{"em":"29/09/2026 14:20","texto":"Aberta por Ana Souza"},{"em":"29/09/2026 16:05","texto":"Encaminhada para Carlos Menezes por Ana Souza"},{"em":"03/10/2026 11:30","texto":"Marcada como corrigida por Carlos Menezes"}]'::jsonb),
((select id from public.obras where codigo = 'U12'), 'NC-003', 'ef099cfe-4e15-4e38-a4e6-92644a8db27c', 103, '1.3', 'Cantos e arestas arredondados (meia-cana executada)', 'Impermeabilização — Áreas Molhadas', 'Banheiro Social · Térreo', 'Média', 'Juliana Prado', 'Pinturas Beta', 'Meia-cana não executada no encontro da parede com o box.', 'Executar a meia-cana com argamassa polimérica antes da manta.', 'aberta', '2026-10-02', null, '[{"em":"02/10/2026 10:45","texto":"Aberta por Ricardo Lopes"}]'::jsonb),
((select id from public.obras where codigo = 'U12'), 'NC-004', 'ef099cfe-4e15-4e38-a4e6-92644a8db27c', 105, '2.2', 'Número de demãos conforme o projeto', 'Impermeabilização — Áreas Molhadas', 'Banheiro Social · Térreo', 'Alta', 'Juliana Prado', 'Pinturas Beta', 'Só 2 demãos aplicadas; o projeto pede 3.', 'Aplicar a terceira demão cruzada e aguardar a cura.', 'encaminhada', '2026-10-02', null, '[{"em":"02/10/2026 10:50","texto":"Aberta por Ricardo Lopes"},{"em":"02/10/2026 11:10","texto":"Encaminhada para Juliana Prado por Ricardo Lopes"}]'::jsonb),
((select id from public.obras where codigo = 'T405'), 'NC-001', '6b54e996-f731-43be-aae5-f8560fab01cf', 102, '1.2', 'Caimento do contrapiso em direção ao ralo conferido', 'Impermeabilização — Áreas Molhadas', 'Piso do tanque · Anel 1', 'Média', 'Rafael Lima', 'Metalúrgica Alfa', 'Caimento invertido em um trecho de 2 m.', 'Regularizar o trecho com argamassa de nivelamento.', 'aberta', '2026-10-03', null, '[{"em":"03/10/2026 15:20","texto":"Aberta por Rafael Lima"}]'::jsonb);

insert into public.gemba_observacoes (obra_id, local, descricao, causa_raiz, acao, desperdicios, prazo, responsavel, empresa, status) values
((select id from public.obras where codigo = 'U12'), 'Rack 3 · Linha L-340', 'Spool 14 soldado fora da tolerância e cortado de novo duas vezes.', 'Desenho de fabricação desatualizado na bancada.', 'Conferir a revisão do desenho antes de cada corte e fixar a lista de revisões na bancada.', '["Retrabalho"]'::jsonb, '2026-10-02', 'Carlos Menezes', 'Metalúrgica Alfa', 'pendente'),
((select id from public.obras where codigo = 'U12'), 'Forno F-101', 'Equipe parada esperando a permissão de trabalho da operação.', 'Permissão só é emitida às 11h, sem pedido antecipado.', 'Pedir a permissão na véspera, no fim do turno.', '["Espera"]'::jsonb, '2026-10-06', 'Juliana Prado', 'Pinturas Beta', 'em_andamento'),
((select id from public.obras where codigo = 'U12'), 'Canteiro · almoxarifado', 'Tubos levados três vezes entre o almoxarifado e a área de pré-montagem.', 'Área de pré-montagem longe do estoque.', 'Mover a bancada de pré-montagem para perto do almoxarifado.', '["Transporte","Movimentação"]'::jsonb, '2026-10-09', 'Ricardo Lopes', 'Elétrica Gama', 'pendente'),
((select id from public.obras where codigo = 'U12'), 'Pátio de pintura', 'Latas de tinta acumuladas além do consumo de duas semanas.', 'Compra em lote grande para ganhar desconto.', 'Ajustar o pedido ao consumo semanal.', '["Estoque","Superprodução"]'::jsonb, null, 'Juliana Prado', 'Pinturas Beta', 'pendente'),
((select id from public.obras where codigo = 'U12'), 'Painel PC-12', 'Mesma folha de inspeção preenchida à mão e depois digitada de novo.', 'Não existe formulário digital no celular.', 'Usar o checklist do app direto no campo.', '["Processo desnecessário","Retrabalho"]'::jsonb, '2026-10-08', 'Ana Souza', 'Elétrica Gama', 'em_andamento'),
((select id from public.obras where codigo = 'U12'), 'Rack 1', 'Isolamento refeito por falta de proteção contra chuva no trecho.', 'Lona de proteção não foi pedida na programação semanal.', 'Incluir proteção contra chuva na programação de curto prazo.', '["Retrabalho"]'::jsonb, '2026-10-01', 'Ricardo Lopes', 'Elétrica Gama', 'resolvido'),
((select id from public.obras where codigo = 'U12'), 'Casa de bombas', 'Soldador volta ao contêiner três vezes por turno buscar ferramenta.', 'Kit de ferramentas incompleto na frente.', 'Montar um kit padrão por frente de solda.', '["Movimentação","Espera"]'::jsonb, '2026-10-04', 'Carlos Menezes', 'Metalúrgica Alfa', 'pendente'),
((select id from public.obras where codigo = 'T405'), 'Costado T-405', 'Chapas empilhadas esperando o guindaste, que atende outra frente.', 'Um único guindaste para duas frentes.', 'Escalonar o uso do guindaste por horário.', '["Espera"]'::jsonb, '2026-10-07', 'Rafael Lima', 'Metalúrgica Alfa', 'pendente'),
((select id from public.obras where codigo = 'T405'), 'Fundo do tanque', 'Solda de junta repetida por ensaio reprovado.', 'Soldador sem requalificação para a posição.', 'Requalificar o soldador antes da próxima junta.', '["Retrabalho"]'::jsonb, null, 'Rafael Lima', 'Metalúrgica Alfa', 'em_andamento');
end $seed$;
